### PR TITLE
Setup Frontend Testing

### PR DESCRIPTION
**Pull request by azboss2021**
**_WHAT DOES THIS PR DO?_**

This PR installs Vitest as a dev dependency in the web directory and allows for the command `npm run test` to get coverage. 

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

#14 

**_HOW DO I TEST OUT THIS PR?_**

Run `npm run test` when in the web directory.

### CODE REVIEW

**Review by Ruaaann — APPROVED** [review]
Was able to successfully run the example test. This will be a very important feature later on in frontend development.

**Review by chrisj117 — APPROVED** [review]
The example test worked for me as well and outputted a coverage report.

**Review by tresimovic — APPROVED** [review]
Looks good, this worked for me as well.

**Review by danielogen — APPROVED** [review]
Tested and working well

**Pull request merged**
