### PR TITLE
Created basic issue template

### PR DESCRIPTION
**Pull request by chrisj117**
**_WHAT DOES THIS PR DO?_**

- Adds an issue template to the repository following the steps outlined in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

 - #24 

**_HOW DO I TEST OUT THIS PR?_**

  - Upon making an issue, the template should be available to users.

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
The issues template is great. Its concise and captures what is required.

**Comment by azboss2021** [comment]
I agree with Daniel. Short but effective 👍

**Review by danielogen — APPROVED** [review]
LGTM

**Review by azboss2021 — APPROVED** [review]
Looks Good

**Pull request merged**
