### PR TITLE
CI Pipeline and Unittesting Setup

### PR DESCRIPTION
**Pull request by danielogen**
**_WHAT DOES THIS PR DO?_**
- Setting CI pipeline and Unittest with Code Coverage. Both API and Web pipeline is written in single `.yaml` file. 
- It also provide integration with `codecov` tool

**_WHAT ISSUES ARE RELATED TO THIS PR?_**
- #14 
- #15 

**_HOW DO I TEST OUT THIS PR?_**
- The CI pipeline can be accessed on the `Actions` tab of this repo.
- To run test locally, `git clone` this repository and `cd` to `api` directory. Now run `coverage run manage.py test && coverage report`.
- For linting,  `cd` to `api` directory and run `flake8`

### CODE REVIEW

**Review by chrisj117 — APPROVED** [review]
After discussing this PR in last meeting, usage of it looks intuitive with how the test checks for changed files in the front(web)/back(api) end, then only runs the needed tests.

**Review by azboss2021 — COMMENTED** [review]
The pipeline you wrote looks great. I don't see any issues. When the frontend is more prepared, we will add that. For now, the backend looks ready

**Review by azboss2021 — APPROVED** [review]

**Comment by danielogen** [comment]
I kind expected this conflict :). Let me solve then we can merge the PR

**Comment by danielogen** [comment]
I have resolved all the merge conflicts

**Pull request merged**
